var collectables = [
    { name: "Flowers", value: 155.50 },
    { name: "Tarot Cups", value: 240.50 },
    { name: "Tarot Swords", value: 286.50 },
    { name: "Tarot Wands", value: 239.00 },
    { name: "Tarot Pentacles", value: 287.00 },
    { name: "Braclets", value: 271.50 },
    { name: "Earrings", value: 364.50 },
    { name: "Necklaces", value: 335.00 },
    { name: "Rings", value: 378.00 },
    { name: "Alcohol", value: 160.50 },
    { name: "Eggs", value: 182.50 },
    { name: "Arrowheads", value: 289.00 },
    { name: "Heirlooms", value: 292.50 },
    { name: "Coins", value: 540.00 },
];

// All spellings are set to match the names searchable for: https://jeanropke.github.io/RDR2CollectorsMap/
var collectableMap = {
    "Flowers": [
        "Texas Bluebonnet",
        "Bitterweed",
        "Agarita",
        "Wild Rhubarb",
        "Cardinal FLower",
        "Creek Plum",
        "Blood Flower",
        "Chocolate Daisy",
        "Wisteria",
    ],

    "Tarot Cups": [
        "Ace of Cups",
        "Two of Cups",
        "Three of Cups",
        "Four of Cups",
        "Five of Cups",
        "Six of Cups",
        "Seven of Cups",
        "Eight of Cups",
        "Nine of Cups",
        "Ten of Cups",
        "Page of Cups",
        "Knight of Cups",
        "Queen of Cups",
        "King of Cups",
    ],
    "Tarot Swords": [
        "Ace of Swords",
        "Two of Swords",
        "Three of Swords",
        "Four of Swords",
        "Five of Swords",
        "Six of Swords",
        "Seven of Swords",
        "Eight of Swords",
        "Nine of Swords",
        "Ten of Swords",
        "Page of Swords",
        "Knight of Swords",
        "Queen of Swords",
        "King of Swords",
    ],
    "Tarot Wands": [
        "Ace of Wands",
        "Two of Wands",
        "Three of Wands",
        "Four of Wands",
        "Five of Wands",
        "Six of Wands",
        "Seven of Wands",
        "Eight of Wands",
        "Nine of Wands",
        "Ten of Wands",
        "Page of Wands",
        "Knight of Wands",
        "Queen of Wands",
        "King of Wands",
    ],
    "Tarot Pentacles": [
        "Ace of Pentacles",
        "Two of Pentacles",
        "Three of Pentacles",
        "Four of Pentacles",
        "Five of Pentacles",
        "Six of Pentacles",
        "Seven of Pentacles",
        "Eight of Pentacles",
        "Nine of Pentacles",
        "Ten of Pentacles",
        "Page of Pentacles",
        "Knight of Pentacles",
        "Queen of Pentacles",
        "King of Pentacles",
    ],
    "Braclets": [
        "Abello Ruby Bangle Bracelet",
        "Ojeda Rose Gold Bangle Bracelet",
        "Helena Sapphire Bracelet",
        "Durant Pearl Bracelet",
        "Infanta Turquoise Bracelet",
        "Elliston Carved Bracelet",
        "Hajnal Garnet Bangle Bracelet",
        "Greco Sapphire Bracelet",
    ],
    "Earrings": [
        "Ursula Citrine Earrings",
        "Royal Victoria Diamond Earrings",
        "Calumet Turquoise Earrings",
        "Orchidee Diamond Earrings",
        "Sterling Tooth Earrings",
        "Harford Garnet Earrings",
        "Duchess Emerald Earrings",
        "Beauchene Ruby Earrings", // Note - no fancy e
        "Endicott Diamond Earrings",
        "Josephine Pearl Earrings",
        "Emmeline Coral Earrings",
    ],
    "Necklaces": [
        "Blakely Miniature Necklace",
        "Richelieu Amethyst Necklace",
        "Pelle Pearl Necklace",
        "Ainsworth Cross Necklace",
        "Braxton Amethyst Necklace",
        "Rou Pearl Necklace",
        "Gosselin White Gold Necklace",
        "Dane Topaz Necklace",
        "Tuamotu Pearl Necklace",
    ],
    "Rings": [
        "Harland Coral Ring",
        "Magnate Turquoise Ring",
        "Pilgrim Moonstone Ring",
        "Bonnard Pearl Ring",
        "Banais Topaz Ring",
        "Beaulieux Diamond Ring",
        "Yates Diamond Ring",
        "Aubrey Onyx Ring",
        "Bosque Emerald Ring",
        "Sackville Diamond Ring",
        "Thorburn Turquoise Ring",
    ],
    "Alcohol": [
        "Tennesee Whiskey", // Note - single s in Tennessee
        "Irish Whiskey",
        "Scotch Whisky", // Note - no e in whiskey
        "Absinthe",
        "Gran Corazon Madeira",
        "Old Tom Gin",
        "Caribbean Rum",
        "Cognac",
        "London Dry Gin",
    ],
    "Eggs": [
        "Spoonbill Egg",
        "Heron Egg",
        "Loon Egg",
        "Eagle Egg",
        "Vulture Egg",
        "Hawk Egg",
        "Egret Egg",
        "Duck Egg",
        "Goose Egg",
    ],
    "Arrowheads": [
        "Rough Arrowhead",
        "Splintered Arrowhead",
        "Crude Arrowhead",
        "Chipped Arrowhead",
        "Feldspar Arrowhead",
        "Slate Arrowhead",
        "Bone Arrowhead",
        "Raw Arrowhead",
        "Obsidian Arrowhead",
        "Quartz Arrowhead",
        "Flint Arrowhead",
        "Agate Arrowhead",
    ],
    "Heirlooms": [
        "Jade Hairpin",
        "Cherrywood Comb",
        "Ebony Hairbrush",
        "Metal Hairpin",
        "Carved Wooden Hairpin",
        "Boxwood Comb",
        "Goat Hair Brush",
        "Ebony Hairpin",
        "Ivory Hairpin",
        "Rosewood Hairbrush",
        "Tortoiseshell Comb",
        "Ivory Comb",
        "Horse Hair Brush",
        "Boar Bristle Brush",
        "New Guinea Rosewood Hairbrush",
    ],
    "Coins": [
        "1800 Gold Quarter",
        "1798 Draped Bust Silver Dollar",
        "1787 One Cent Token",
        "1794 Silver Dollar",
        "1700 New Yorke Token",
        "1800 Five Dollar Bechtler",
        "1792 Quarter",
        "1800 Gold Dollar",
        "1792 Nickel",
        "1796 Halfpenny",
        "1795 Half Eagle",
        "1797 Gold Eagle",
        "1792 Liberty Quarter",
        "1800 Half Dime",
        "1789 Penny",
    ]
}

// ---------------------------------------
// --------------- PRICING ---------------
// ---------------------------------------
var collectablePricingMap = {
    // Flowers
    "Texas Bluebonnet": 8.5,
    "Bitterweed": 8.5,
    "Agarita": 10.5,
    "Wild Rhubarb": 7.25,
    "Cardinal FLower": 7,
    "Creek Plum": 10.25,
    "Blood Flower": 10.25,
    "Chocolate Daisy": 7.25,
    "Wisteria": 8.25,

    // Tarot Cups
    "Ace of Cups": 12,
    "Two of Cups": 7.75,
    "Three of Cups": 7.75,
    "Four of Cups": 7.75,
    "Five of Cups": 8,
    "Six of Cups": 8,
    "Seven of Cups": 7.5,
    "Eight of Cups": 7.75,
    "Nine of Cups": 7.75,
    "Ten of Cups": 7.5,
    "Page of Cups": 8.5,
    "Knight of Cups": 9,
    "Queen of Cups": 10,
    "King of Cups": 11,

    // Tarot Swords
    "Ace of Swords": 14.5,
    "Two of Swords": 9.5,
    "Three of Swords": 9.25,
    "Four of Swords": 9.25,
    "Five of Swords": 9.25,
    "Six of Swords": 9,
    "Seven of Swords": 9,
    "Eight of Swords": 9,
    "Nine of Swords": 9.25,
    "Ten of Swords": 9,
    "Page of Swords": 10,
    "Knight of Swords": 11,
    "Queen of Swords": 12,
    "King of Swords": 13.25,

    // Tarot Wands
    "Ace of Wands": 12,
    "Two of Wands": 7.5,
    "Three of Wands": 7.5,
    "Four of Wands": 8,
    "Five of Wands": 7.75,
    "Six of Wands": 7.25,
    "Seven of Wands": 7.5,
    "Eight of Wands": 7.75,
    "Nine of Wands": 7.75,
    "Ten of Wands": 8,
    "Page of Wands": 8.5,
    "Knight of Wands": 9,
    "Queen of Wands": 10,
    "King of Wands": 11,

    // Tarot Pentacles
    "Ace of Pentacles": 14.5,
    "Two of Pentacles": 9,
    "Three of Pentacles": 9.5,
    "Four of Pentacles": 9.25,
    "Five of Pentacles": 9.25,
    "Six of Pentacles": 9,
    "Seven of Pentacles": 9,
    "Eight of Pentacles": 9,
    "Nine of Pentacles": 9.5,
    "Ten of Pentacles": 9.25,
    "Page of Pentacles": 10,
    "Knight of Pentacles": 11,
    "Queen of Pentacles": 12,
    "King of Pentacles": 13.25,

    // Braclets
    "Abello Ruby Bangle Bracelet": 17,
    "Ojeda Rose Gold Bangle Bracelet": 17,
    "Helena Sapphire Bracelet": 17.75,
    "Durant Pearl Bracelet": 16.5,
    "Infanta Turquoise Bracelet": 16.75,
    "Elliston Carved Bracelet": 16.5,
    "Hajnal Garnet Bangle Bracelet": 16.25,
    "Greco Sapphire Bracelet": 18,

    // Earrings
    "Ursula Citrine Earrings": 15.5,
    "Royal Victoria Diamond Earrings": 17.25,
    "Calumet Turquoise Earrings": 15.75,
    "Orchidee Diamond Earrings": 18.5,
    "Sterling Tooth Earrings": 15.5,
    "Harford Garnet Earrings": 16,
    "Duchess Emerald Earrings": 15.75,
    "Beauchene Ruby Earrings": 16.5,
    "Endicott Diamond Earrings": 19.25,
    "Josephine Pearl Earrings": 16,
    "Emmeline Coral Earrings": 16.25,

    // Necklaces
    "Blakely Miniature Necklace": 18.75,
    "Richelieu Amethyst Necklace": 17.75,
    "Pelle Pearl Necklace": 18.25,
    "Ainsworth Cross Necklace": 17.25,
    "Braxton Amethyst Necklace": 18,
    "Rou Pearl Necklace": 18.5,
    "Gosselin White Gold Necklace": 19.5,
    "Dane Topaz Necklace": 18.75,
    "Tuamotu Pearl Necklace": 20.75,

    // Rings
    "Harland Coral Ring": 16.75,
    "Magnate Turquoise Ring": 16.5,
    "Pilgrim Moonstone Ring": 16.75,
    "Bonnard Pearl Ring": 16.75,
    "Banais Topaz Ring": 17,
    "Beaulieux Diamond Ring": 18.5,
    "Yates Diamond Ring": 17.75,
    "Aubrey Onyx Ring": 16.5,
    "Bosque Emerald Ring": 16.5,
    "Sackville Diamond Ring": 19.25,
    "Thorburn Turquoise Ring": 16.75,

    // Alcohol
    "Tennesee Whiskey": 7.25,
    "Irish Whiskey": 10.25,
    "Scotch Whisky": 10.5,
    "Absinthe": 9,
    "Gran Corazon Madeira": 9,
    "Old Tom Gin": 10.5,
    "Caribbean Rum": 7.75,
    "Cognac": 8.75,
    "London Dry Gin": 7.25,

    // Eggs
    "Spoonbill Egg": 0,
    "Heron Egg": 0,
    "Loon Egg": 0,
    "Eagle Egg": 0,
    "Vulture Egg": 0,
    "Hawk Egg": 0,
    "Egret Egg": 0,
    "Duck Egg": 2.25,
    "Goose Egg": 3,

    // Arrowheads
    "Rough Arrowhead": 11.75,
    "Splintered Arrowhead": 8.75,
    "Crude Arrowhead": 9.5,
    "Chipped Arrowhead": 8.25,
    "Feldspar Arrowhead": 13,
    "Slate Arrowhead": 12,
    "Bone Arrowhead": 12.5,
    "Raw Arrowhead": 9,
    "Obsidian Arrowhead": 17,
    "Quartz Arrowhead": 16.25,
    "Flint Arrowhead": 11.25,
    "Agate Arrowhead": 15.25,

    // Heirlooms
    "Jade Hairpin": 11.75,
    "Cherrywood Comb": 8.75,
    "Ebony Hairbrush": 9,
    "Metal Hairpin": 10.5,
    "Carved Wooden Hairpin": 10,
    "Boxwood Comb": 8.75,
    "Goat Hair Brush": 8.5,
    "Ebony Hairpin": 12.25,
    "Ivory Hairpin": 13,
    "Rosewood Hairbrush": 8,
    "Tortoiseshell Comb": 8.25,
    "Ivory Comb": 9.75,
    "Horse Hair Brush": 9.25,
    "Boar Bristle Brush": 9,
    "New Guinea Rosewood Hairbrush": 9.5,

    // Coins
    "1800 Gold Quarter": 21,
    "1798 Draped Bust Silver Dollar": 18.25,
    "1787 One Cent Token": 18,
    "1794 Silver Dollar": 19,
    "1700 New Yorke Token": 20.25,
    "1800 Five Dollar Bechtler": 17.75,
    "1792 Quarter": 14.5,
    "1800 Gold Dollar": 22,
    "1792 Nickel": 14.25,
    "1796 Halfpenny": 14.75,
    "1795 Half Eagle": 15,
    "1797 Gold Eagle": 21.25,
    "1792 Liberty Quarter": 20.75,
    "1800 Half Dime": 18.5,
    "1789 Penny": 14.75,
}